import { useEffect, useState, useSyncExternalStore } from 'react'

import { isGeneratedPath } from '../../../shared/generatedPaths'

// A world's answer, so a tab switched back to does not ask again.
const markedByWorld = new Map<string, { key: string; generated: ReadonlySet<string> }>()
const MAX_REMEMBERED_WORLDS = 32
const ASK_DELAY_MS = 120

// Every path is in the key: two lists of one length and the same ends are
// still different reviews. Hashed once per list.
const keyedPaths = new WeakMap<readonly string[], string>()
function pathsKey(paths: readonly string[]): string {
  let key = keyedPaths.get(paths)
  if (key != null) return key
  let hash = 0x811c9dc5
  for (const path of paths) {
    for (let index = 0; index < path.length; index += 1) {
      hash ^= path.charCodeAt(index)
      hash = Math.imul(hash, 0x01000193)
    }
    hash ^= 10
    hash = Math.imul(hash, 0x01000193)
  }
  key = `${paths.length}:${(hash >>> 0).toString(36)}`
  keyedPaths.set(paths, key)
  return key
}

/** What the attributes said about a working tree's changed files, for the tree's "Hide generated". */
interface WorkingTreeMarks {
  asked: ReadonlySet<string>
  generated: ReadonlySet<string>
  test: (path: string) => boolean
}
const workingTreeMarks = new Map<string, WorkingTreeMarks>()
const workingTreeListeners = new Set<() => void>()

function rememberWorkingTreeMarks(root: string, asked: readonly string[], generated: ReadonlySet<string>): void {
  const askedSet = new Set(asked)
  workingTreeMarks.delete(root)
  workingTreeMarks.set(root, {
    asked: askedSet,
    generated,
    test: (path) => askedSet.has(path) ? generated.has(path) : isGeneratedPath(path)
  })
  while (workingTreeMarks.size > MAX_REMEMBERED_WORLDS) {
    const oldest = workingTreeMarks.keys().next().value
    if (oldest == null) break
    workingTreeMarks.delete(oldest)
  }
  for (const listener of workingTreeListeners) listener()
}

function subscribeWorkingTreeMarks(listener: () => void): () => void {
  workingTreeListeners.add(listener)
  return () => { workingTreeListeners.delete(listener) }
}

/**
 * Whether a path in this working tree is generated: by `.gitattributes` for a
 * changed file the review has asked about, by its path otherwise. A new
 * function when an answer lands, so a filter keyed on it reruns.
 */
export function useGeneratedPathTest(root: string | null | undefined): (path: string) => boolean {
  const read = (): (path: string) => boolean => (root == null ? undefined : workingTreeMarks.get(root)?.test) ?? isGeneratedPath
  return useSyncExternalStore(subscribeWorkingTreeMarks, read, read)
}

function rememberMarks(worldId: string, key: string, generated: ReadonlySet<string>): void {
  markedByWorld.delete(worldId)
  markedByWorld.set(worldId, { key, generated })
  while (markedByWorld.size > MAX_REMEMBERED_WORLDS) {
    const oldest = markedByWorld.keys().next().value
    if (oldest == null) break
    markedByWorld.delete(oldest)
  }
}

/**
 * The review's generated files as `.gitattributes` decides them (main's
 * `git check-attr`, at the review's head where git can). Null until main
 * answers; the path heuristics cover lockfiles and snapshots meanwhile.
 */
export function useReviewFileMarks(
  worldId: string | null | undefined,
  root: string | null | undefined,
  paths: readonly string[],
  revision: string | null
): ReadonlySet<string> | null {
  const key = `${root ?? ''}\n${revision ?? ''}\n${pathsKey(paths)}`
  const remembered = worldId == null ? undefined : markedByWorld.get(worldId)
  const [answer, setAnswer] = useState<{ key: string; generated: ReadonlySet<string> } | null>(null)
  useEffect(() => {
    if (worldId == null || root == null || paths.length === 0 || window.repository == null) return
    if (markedByWorld.get(worldId)?.key === key) return
    let cancelled = false
    const timer = window.setTimeout(() => {
      void window.repository?.getReviewFileMarks(root, paths, revision).then((reply) => {
        // No answer (too many files, or the folder is gone): the heuristics stay.
        if (reply == null) return
        const generated = new Set(reply.generated)
        rememberMarks(worldId, key, generated)
        if (revision == null) rememberWorkingTreeMarks(root, paths, generated)
        if (!cancelled) setAnswer({ key, generated })
      }, () => {})
    }, ASK_DELAY_MS)
    return () => {
      cancelled = true
      window.clearTimeout(timer)
    }
  }, [key, paths, revision, root, worldId])
  if (answer?.key === key) return answer.generated
  return remembered?.key === key ? remembered.generated : null
}

/** Generated by the repository's attributes once they have answered, by its path until then. */
export function isGeneratedReviewPath(path: string, marked: ReadonlySet<string> | null): boolean {
  return marked == null ? isGeneratedPath(path) : marked.has(path)
}

// What each world decided per item: a generated file starts collapsed once,
// and a reader who opens it keeps it open. A decision made on the heuristics
// alone is provisional: when the attributes answer, it follows them, unless
// the reader has toggled the file since.
interface GeneratedDecision {
  collapsed: boolean
  provisional: boolean
}
const decidedByWorld = new Map<string, Map<string, GeneratedDecision>>()

export interface GeneratedCollapseChange {
  collapse: string[]
  expand: string[]
}

/** The items to fold or open: new ones by whether they are generated, provisional ones once the attributes answer. */
export function generatedCollapseChanges(
  worldId: string,
  itemIds: readonly string[],
  pathOf: (itemId: string) => string,
  marked: ReadonlySet<string> | null,
  collapsedIds: ReadonlySet<string>
): GeneratedCollapseChange {
  let decided = decidedByWorld.get(worldId)
  if (decided == null) {
    decided = new Map()
    decidedByWorld.set(worldId, decided)
    while (decidedByWorld.size > MAX_REMEMBERED_WORLDS * 4) {
      const oldest = decidedByWorld.keys().next().value
      if (oldest == null) break
      decidedByWorld.delete(oldest)
    }
  }
  const change: GeneratedCollapseChange = { collapse: [], expand: [] }
  for (const id of itemIds) {
    const generated = isGeneratedReviewPath(pathOf(id), marked)
    const previous = decided.get(id)
    if (previous == null) {
      decided.set(id, { collapsed: generated, provisional: marked == null })
      if (generated) change.collapse.push(id)
      continue
    }
    if (!previous.provisional || marked == null) continue
    previous.provisional = false
    // Toggled by the reader since: theirs to keep.
    if (collapsedIds.has(id) !== previous.collapsed || generated === previous.collapsed) continue
    previous.collapsed = generated
    if (generated) change.collapse.push(id)
    else change.expand.push(id)
  }
  return change
}
